// website/public/feature-examples.json is generated by
// scripts/generate-feature-examples.ts and describes, per landing-page
// feature row, whether the compiler actually compiles (and — for `noCompile`
// rows — SHOULD NOT even attempt to compile) the example shown.
//
// Found stale 2026-08: the artifact hadn't been regenerated since 2026-06-11
// while the compiler kept landing PRs. 24 rows were flagged `noCompile: true`
// with code comments like "// not supported" — nine of them, re-verified by
// hand against the live compiler, now compile and run CORRECTLY end to end
// (e.g. HTML string methods measured 100% test262, RegExp v-flag 98%). Their
// own `js` snippets contradicted their own `badge`/`noCompile` status.
//
// These tests don't try to re-verify compiler behavior (that already happened
// by hand for this pass, cross-checked against fresh test262 pass rates where
// available — see the commit this file landed in). They pin the CONSISTENCY
// invariants that let that kind of drift go undetected for two months:
//   1. a row that compiles must not show "not supported" prose,
//   2. a row that FAILS to compile (attempted, not skipped) is always a bug —
//      the generator either compiles cleanly or is told to skip in advance,
//   3. every noCompile row's own explain/comment describes what ACTUALLY
//      happens (compiles-but-wrong vs. genuinely rejected), not a guess.
// None of this can catch a NEW drift by itself — that needs the generator to
// run again — but it stops a stale artifact from being silently inconsistent
// with itself in the meantime.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname ?? ".", "..");
const EXAMPLES_PATH = join(ROOT, "website", "public", "feature-examples.json");

interface FeatureRow {
  name: string;
  edition: string;
  badge: "full" | "partial" | "none";
  description: string;
  js: string;
  wat: string | null;
  compileSuccess: boolean;
  compileError?: string;
  noCompile?: boolean;
  passCount?: number;
  totalCount?: number;
}

const data = JSON.parse(readFileSync(EXAMPLES_PATH, "utf-8")) as {
  generated: string;
  features_generated: string;
  features: FeatureRow[];
};

// Comments that only make sense on a row the compiler genuinely rejects or
// mishandles. A row whose OWN example compiles and runs must not carry one —
// that is the exact contradiction this file exists to prevent ("green
// checkmark" data next to a "not supported" code comment).
const UNSUPPORTED_MARKERS = ["not supported", "not yet", "not possible"];

describe("feature-examples.json — internal consistency", () => {
  it("loads with the expected shape", () => {
    expect(Array.isArray(data.features)).toBe(true);
    expect(data.features.length).toBeGreaterThan(50);
  });

  it("never claims 'not supported' in the code of a row that compiles cleanly", () => {
    const offenders: string[] = [];
    for (const f of data.features) {
      if (f.noCompile || !f.compileSuccess) continue;
      const lower = f.js.toLowerCase();
      if (UNSUPPORTED_MARKERS.some((m) => lower.includes(m))) offenders.push(f.name);
    }
    expect(
      offenders,
      `rows whose example compiles but whose code comment claims otherwise: ${offenders.join(", ")}`,
    ).toEqual([]);
  });

  it("has zero unexpected compile failures — every row either compiles or is deliberately skipped", () => {
    // A row that attempted compilation and failed is always either a real bug
    // (fix the compiler or the snippet) or a row that should have been marked
    // `noCompile` in the first place — never a state to ship silently.
    const unexpected = data.features.filter((f) => !f.noCompile && !f.compileSuccess).map((f) => f.name);
    expect(unexpected, `unexpected compile failures: ${unexpected.join(", ")}`).toEqual([]);
  });

  it("gives every noCompile row an explanation of what actually happens", () => {
    // A bare "not supported" with no elaboration was the pre-fix norm for
    // rows that, on inspection, actually compiled and just produced the wrong
    // answer. Requiring `explain` doesn't verify accuracy, but it does force
    // a human to have looked, and keeps the row auditable.
    const missing = data.features.filter((f) => f.noCompile).filter((f) => !("explain" in f));
    // Exempt: fully speculative TC39 proposals with no compiler engagement at
    // all, where "not yet a language feature" needs no further explanation.
    // Everything that at least reaches the compiler should have one.
    const exempt = new Set(["Decorators", "Pattern matching", "Temporal"]);
    const unexplained = missing.map((f) => f.name).filter((n) => !exempt.has(n));
    expect(unexplained, `noCompile rows with no explain text: ${unexplained.join(", ")}`).toEqual([]);
  });

  it("keeps compileSuccess/wat internally consistent with noCompile", () => {
    for (const f of data.features) {
      if (f.noCompile) {
        expect(f.compileSuccess, `${f.name}: noCompile row must have compileSuccess=false`).toBe(false);
        expect(f.wat, `${f.name}: noCompile row must have wat=null`).toBeNull();
      }
    }
  });

  it("only uses the three documented badge values", () => {
    const bad = data.features.filter((f) => !["full", "partial", "none"].includes(f.badge));
    expect(bad.map((f) => f.name)).toEqual([]);
  });
});
