#!/usr/bin/env bash
# make-nm-host.sh (#2812) — emit a turnkey Chrome Native Messaging host from a
# js2wasm-compiled `.wasm` module: a runner the browser can launch + a host
# manifest whose `path` points at that runner (absolute, as Chrome requires).
#
# The runner is the executable Chrome invokes per the host manifest. This script
# supports the two runners the acceptance criteria require — a `wasmtime`
# shebang script and a `bun -b` shebang script — plus an optional `--preload`
# for `--link node:fs` modules. (`deno compile` produces a self-contained
# binary directly; see examples/native-messaging/README.md for that path.)
#
# Usage:
#   ./make-nm-host.sh --wasm out/host.wasm --name com.example.host \
#       --origin chrome-extension://YOUR_EXTENSION_ID/ [options]
#
# Options:
#   --wasm PATH        Path to the compiled host `.wasm` (required).
#   --name NAME        Native-messaging host name. The manifest filename Chrome
#                      scans for MUST equal this (default: derived from --wasm).
#   --origin ORIGIN    An allowed extension origin, e.g.
#                      chrome-extension://<EXTENSION_ID>/  (repeatable).
#   --runner R         wasmtime | bun   (default: wasmtime).
#   --preload NS=FILE  Register a runtime import provider (e.g.
#                      node:fs=node-fs.wasm) for a `--link node:fs` module.
#                      Repeatable. wasmtime only; ignored with a warning for bun.
#   --outdir DIR       Where to write the runner + manifest (default: alongside
#                      the .wasm).
#   -h, --help         Show this help.
#
# Output (in --outdir):
#   <name>.runner.sh   The executable Chrome launches (chmod +x, absolute paths).
#   <name>.json        The Chrome host manifest (absolute `path` → the runner).
#
# Install the manifest into Chrome's per-platform NativeMessagingHosts directory
# (README.md "Wire it into the browser" has the exact locations) and set the
# manifest `allowed_origins`. Nothing here is browser-specific beyond the
# manifest schema; Firefox/Edge use the same `.json` shape.
set -euo pipefail

WASM="" NAME="" RUNNER="wasmtime" OUTDIR=""
ORIGINS=()
PRELOADS=()

die() { echo "make-nm-host: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --wasm)    WASM="${2:?--wasm needs a value}"; shift 2 ;;
    --name)    NAME="${2:?--name needs a value}"; shift 2 ;;
    --origin)  ORIGINS+=("${2:?--origin needs a value}"); shift 2 ;;
    --runner)  RUNNER="${2:?--runner needs a value}"; shift 2 ;;
    --preload) PRELOADS+=("${2:?--preload needs a value}"); shift 2 ;;
    --outdir)  OUTDIR="${2:?--outdir needs a value}"; shift 2 ;;
    -h|--help) sed -n '2,45p' "$0"; exit 0 ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

[ -n "$WASM" ] || die "--wasm is required (see --help)"
[ -f "$WASM" ] || die "no such file: $WASM"
case "$RUNNER" in wasmtime|bun) ;; *) die "--runner must be wasmtime or bun" ;; esac

# Absolute paths — Chrome launches the host with no predictable working dir.
ABS_WASM="$(cd "$(dirname "$WASM")" && pwd)/$(basename "$WASM")"
[ -n "$NAME" ] || NAME="$(basename "$WASM" .wasm)"
[ -n "$OUTDIR" ] || OUTDIR="$(dirname "$ABS_WASM")"
mkdir -p "$OUTDIR"
ABS_OUTDIR="$(cd "$OUTDIR" && pwd)"

RUNNER_PATH="$ABS_OUTDIR/$NAME.runner.sh"
MANIFEST_PATH="$ABS_OUTDIR/$NAME.json"

# The exact WasmGC proposal flags the js2wasm --target wasi codegen relies on.
# NOT `-W all-proposals=y`: that also turns on stack-switching, which wasmtime
# 44/45 rejects at module load, so the host would exit before running.
WASMTIME_FLAGS="gc=y,function-references=y,tail-call=y,exceptions=y"

# Absolutize each --preload NS=FILE file argument.
abs_preload() {
  local spec="$1" ns file
  ns="${spec%%=*}"; file="${spec#*=}"
  [ "$ns" != "$spec" ] || die "--preload must be NS=FILE, got: $spec"
  [ -f "$file" ] || die "--preload file not found: $file"
  printf '%s=%s' "$ns" "$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
}

if [ "$RUNNER" = "wasmtime" ]; then
  PRELOAD_ARGS=""
  for p in ${PRELOADS[@]+"${PRELOADS[@]}"}; do
    PRELOAD_ARGS+=" --preload $(abs_preload "$p")"
  done
  cat > "$RUNNER_PATH" <<EOF
#!/usr/bin/env bash
# Generated by make-nm-host.sh (#2812). Chrome launches this to run the host.
# Uses the targeted WasmGC proposal flags — NOT -W all-proposals=y (that enables
# stack-switching, which wasmtime rejects). wasmtime must be on PATH.
exec wasmtime run -W $WASMTIME_FLAGS$PRELOAD_ARGS "$ABS_WASM" "\$@"
EOF
else
  if [ "${#PRELOADS[@]}" -gt 0 ]; then
    echo "make-nm-host: warning: --preload is wasmtime-only; ignoring for bun." >&2
    echo "  (bun -b runs a self-contained module; link node:fs at compile time or use wasmtime.)" >&2
  fi
  cat > "$RUNNER_PATH" <<EOF
#!/usr/bin/env bash
# Generated by make-nm-host.sh (#2812). Chrome launches this to run the host.
# bun -b executes the WasmGC module directly; the required proposals are on by
# default. bun must be on PATH.
exec bun -b "$ABS_WASM" "\$@"
EOF
fi
chmod +x "$RUNNER_PATH"

# Build the allowed_origins JSON array (default to a placeholder if none given).
if [ "${#ORIGINS[@]}" -eq 0 ]; then
  ORIGINS=("chrome-extension://YOUR_EXTENSION_ID/")
  echo "make-nm-host: no --origin given; wrote a placeholder allowed_origins." >&2
fi
origins_json=""
for o in "${ORIGINS[@]}"; do
  [ -z "$origins_json" ] && origins_json="\"$o\"" || origins_json="$origins_json, \"$o\""
done

cat > "$MANIFEST_PATH" <<EOF
{
  "name": "$NAME",
  "description": "js2wasm Native Messaging host ($RUNNER)",
  "path": "$RUNNER_PATH",
  "type": "stdio",
  "allowed_origins": [$origins_json]
}
EOF

echo "Wrote runner : $RUNNER_PATH"
echo "Wrote manifest: $MANIFEST_PATH"
echo
echo "Next steps:"
echo "  1. Set allowed_origins in the manifest to your extension's origin(s)."
echo "  2. Copy $NAME.json into Chrome's NativeMessagingHosts dir (see README.md)."
echo "  3. Smoke-test the wire protocol:"
echo "     printf '\\x0d\\x00\\x00\\x00{\"ping\":true}' | \"$RUNNER_PATH\""
