// Copyright (c) 2026 Loopdive GmbH. Licensed under Apache-2.0 WITH LLVM-exception.

export {
  PURE_MATH_RUNTIME_FEATURES,
  NUMERIC_COERCION_RUNTIME_FEATURES,
  NUMBER_BOUNDARY_RUNTIME_FEATURES,
  BOOLEAN_BOUNDARY_RUNTIME_FEATURES,
  EXTERN_BOUNDARY_RUNTIME_FEATURES,
  INTRINSIC_RUNTIME_FEATURES,
  PURE_MATH_HOST_CAPABILITIES,
} from "./contracts/intrinsics.js";
export type {
  PureMathRuntimeFeature,
  NumericCoercionRuntimeFeature,
  NumberBoundaryRuntimeFeature,
  BooleanBoundaryRuntimeFeature,
  ExternBoundaryRuntimeFeature,
  RuntimeFeature as IntrinsicRuntimeFeature,
  HostCapability,
  IntrinsicSignature,
  IntrinsicSourceLocation,
  IntrinsicUse,
  IntrinsicDefinition,
  IntrinsicVerificationCode,
  IntrinsicVerificationFailure,
} from "./contracts/intrinsics.js";

export {
  RUNTIME_BACKEND_REQUIREMENTS,
  PURE_MATH_RUNTIME_PROVIDER_IDS,
  NUMERIC_COERCION_RUNTIME_PROVIDER_IDS,
  NUMBER_BOUNDARY_RUNTIME_PROVIDER_IDS,
  BOOLEAN_BOUNDARY_RUNTIME_PROVIDER_IDS,
  EXTERN_BOUNDARY_RUNTIME_PROVIDER_IDS,
  GENERATOR_NUMBER_BOX_RUNTIME_FEATURES,
  GENERATOR_NUMBER_BOX_RUNTIME_PROVIDER_IDS,
  STRING_COMPARE_RUNTIME_FEATURES,
  STRING_COMPARE_RUNTIME_PROVIDER_IDS,
  STRING_EQ_RUNTIME_FEATURES,
  STRING_EQ_RUNTIME_PROVIDER_IDS,
  STRING_LEN_RUNTIME_FEATURES,
  STRING_LEN_RUNTIME_PROVIDER_IDS,
  STRING_CONCAT_RUNTIME_FEATURES,
  STRING_CONCAT_RUNTIME_PROVIDER_IDS,
  STRING_CHAR_CODE_AT_RUNTIME_FEATURES,
  STRING_CHAR_CODE_AT_RUNTIME_PROVIDER_IDS,
  STRING_CONCAT_MANY_RUNTIME_FEATURES,
  STRING_CONCAT_MANY_RUNTIME_PROVIDER_IDS,
  STRING_CONCAT_MANY_NATIVE_ARITY,
  STRING_CONST_RUNTIME_FEATURES,
  STRING_CONST_RUNTIME_PROVIDER_IDS,
  HOST_CALLBACK_WRAP_RUNTIME_FEATURES,
  HOST_CALLBACK_WRAP_RUNTIME_PROVIDER_IDS,
  FUNCTION_PROTOTYPE_CALL_RUNTIME_FEATURES,
  FUNCTION_PROTOTYPE_CALL_RUNTIME_PROVIDER_IDS,
  REFERENCE_ERROR_RUNTIME_FEATURES,
  REFERENCE_ERROR_RUNTIME_PROVIDER_IDS,
} from "./contracts/manifest.js";
export type {
  RuntimeFeature,
  HostCapabilityId,
  RuntimeBackendRequirement,
  MathRuntimeProviderId,
  NumericCoercionRuntimeProviderId,
  NumberBoundaryRuntimeProviderId,
  BooleanBoundaryRuntimeProviderId,
  ExternBoundaryRuntimeProviderId,
  GeneratorNumberBoxRuntimeFeature,
  GeneratorNumberBoxRuntimeProviderId,
  StringCompareRuntimeFeature,
  StringCompareRuntimeProviderId,
  StringEqRuntimeFeature,
  StringEqRuntimeProviderId,
  StringLenRuntimeFeature,
  StringLenRuntimeProviderId,
  StringConcatRuntimeFeature,
  StringConcatRuntimeProviderId,
  StringCharCodeAtRuntimeFeature,
  StringCharCodeAtRuntimeProviderId,
  StringConcatManyRuntimeFeature,
  StringConcatManyRuntimeProviderId,
  StringConstRuntimeFeature,
  StringConstRuntimeProviderId,
  HostCallbackWrapRuntimeFeature,
  HostCallbackWrapRuntimeProviderId,
  FunctionPrototypeCallRuntimeFeature,
  FunctionPrototypeCallRuntimeProviderId,
  ReferenceErrorRuntimeFeature,
  ReferenceErrorRuntimeProviderId,
  RuntimeProviderId,
  RuntimeProviderImplementation,
  MathRuntimeProviderImplementation,
  IntrinsicRuntimeProviderImplementation,
  RuntimeProviderDefinition,
  RuntimeProviderPlan,
  RuntimeProviderComponent,
  FrozenRuntimeManifest,
} from "./contracts/manifest.js";

export type {
  PreparedIrFunction,
  PreparedIrModule,
  PreparedIrAsyncHostAdapter,
  PreparedIrAsyncRuntime,
  CurrentPreparedIrAsyncRuntime,
  PreparedIrRuntimeManifest,
} from "./contracts/prepared.js";
