/**
 * Compiler worker — uses pre-bundled compiler JS.
 * No tsx/loader needed. Bundle generated by: npx esbuild src/index.ts --bundle --platform=node --format=esm --outfile=scripts/compiler-bundle.mjs --external:typescript
 *
 * Uses incremental compilation via TS Language Service to cache parsed lib files
 * across compilations. First compilation is cold (~normal speed), subsequent ones
 * skip lib re-parsing for a significant speedup.
 */
import { parentPort } from "node:worker_threads";
import { compile, createIncrementalCompiler } from "./compiler-bundle.mjs";

let compileCount = 0;
const GC_INTERVAL = 25; // GC every 25 compilations to cap memory growth
const RECREATE_INTERVAL = 200; // Recreate incremental compiler to release oldProgram AST

const INCREMENTAL_OPTS = {
  fileName: "test.ts",
  sourceMap: true,
  sourceMapUrl: "test.wasm.map",
  emitWat: false,
  skipSemanticDiagnostics: true,
};

// Incremental compiler — reuses parsed lib SourceFiles via oldProgram.
// Fresh checker per compilation (no state leakage), cached lib parses (fast).
// Recreated every RECREATE_INTERVAL to release accumulated AST memory.
let incrementalCompiler = null;
function createFreshCompiler() {
  try {
    incrementalCompiler = createIncrementalCompiler(INCREMENTAL_OPTS);
  } catch (e) {
    incrementalCompiler = null;
  }
}
createFreshCompiler();

parentPort.on("message", async (msg) => {
  const start = performance.now();
  try {
    const compileFn = incrementalCompiler ? incrementalCompiler.compile : compile;
    const result = incrementalCompiler
      ? await compileFn(msg.source, {
          sourceMapUrl: msg.sourceMapUrl || "test.wasm.map",
        })
      : await compile(msg.source, {
          fileName: "test.ts",
          sourceMap: true,
          sourceMapUrl: msg.sourceMapUrl || "test.wasm.map",
          emitWat: false,
          skipSemanticDiagnostics: true,
        });
    const compileMs = performance.now() - start;

    if (!result.success || result.errors.some((e) => e.severity === "error")) {
      const errMsg = result.errors
        .filter((e) => e.severity === "error")
        .map((e) => `L${e.line}:${e.column} ${e.message}`)
        .join("; ");
      // Include TS diagnostic codes for early error detection
      const errorCodes = result.errors.filter((e) => e.severity === "error" && e.code).map((e) => e.code);
      parentPort.postMessage({ id: msg.id, ok: false, error: errMsg || "unknown", errorCodes, compileMs });
      return;
    }

    parentPort.postMessage({
      id: msg.id,
      ok: true,
      binary: result.binary,
      stringPool: result.stringPool,
      imports: result.imports,
      sourceMap: result.sourceMap || null,
      compileMs,
    });
  } catch (err) {
    parentPort.postMessage({
      id: msg.id,
      ok: false,
      error: err.message || String(err),
      compileMs: performance.now() - start,
    });
  }

  compileCount++;
  // Recreate incremental compiler to release oldProgram AST + type checker state
  if (compileCount % RECREATE_INTERVAL === 0) {
    incrementalCompiler = null;
    if (typeof globalThis.gc === "function") globalThis.gc();
    createFreshCompiler();
  } else if (compileCount % GC_INTERVAL === 0 && typeof globalThis.gc === "function") {
    globalThis.gc();
  }
});

parentPort.postMessage({ type: "ready", pid: process.pid });
