// Copyright (c) 2026 Loopdive GmbH. Licensed under Apache-2.0 WITH LLVM-exception.

// Compatibility exports retain the canonical implementation and authority identities.

export {
  RUNTIME_HOST_CAPABILITY_FUNC_IDS,
  RUNTIME_HOST_CAPABILITY_FUNC_FAMILY_IDS,
  RUNTIME_HOST_CAPABILITY_GLOBAL_IDS,
  RUNTIME_HOST_CAPABILITY_EXPORT_IDS,
  RUNTIME_HOST_CAPABILITY_IDS,
  RUNTIME_HOST_CAPABILITY_FUNC_MODULES,
  RUNTIME_HOST_CAPABILITY_GLOBAL_MODULES,
  RUNTIME_HOST_CAPABILITY_KINDS,
  RUNTIME_HOST_CAPABILITY_FIELD_SCHEMES,
  RUNTIME_HOST_CAPABILITY_FUNC_FAMILY_FIELD_SCHEMES,
  RUNTIME_HOST_CAPABILITY_EXPORT_PUBLICATIONS,
  RUNTIME_HOST_CAPABILITY_HOST_SELECTION_ENV_VARS,
  RUNTIME_HOST_CAPABILITY_HOST_SELECTIONS,
  HOST_CALLBACK_EXCEPTION_POLICY,
  isRuntimeHostCapabilityId,
  isRuntimeHostCapabilityFuncId,
  isRuntimeHostCapabilityFuncFamilyId,
  isRuntimeHostCapabilityGlobalId,
  isRuntimeHostCapabilityExportId,
  RUNTIME_HOST_CAPABILITY_RECORDS,
  assertRuntimeHostCapabilityRecord,
  assertCanonicalRuntimeHostCapabilityRecord,
  asCallableRuntimeHostCapabilityRecord,
  canonicalizeRuntimeHostCapabilityCatalog,
  resolveRuntimeHostCapabilityRecord,
  resolveRuntimeHostCapabilityFuncFamilyRecord,
  resolveRuntimeHostCapabilityGlobalRecord,
  resolveRuntimeHostCapabilityExportRecord,
  resolveRuntimeHostCapabilityFuncRecord,
  HOST_CALLBACK_WRAP_CAPABILITY_RECORD,
} from "./runtime/host-capabilities.js";
export type {
  RuntimeHostCapabilityFuncId,
  RuntimeHostCapabilityFuncFamilyId,
  RuntimeHostCapabilityGlobalId,
  RuntimeHostCapabilityExportId,
  RuntimeHostCapabilityId,
  RuntimeHostCapabilityValueType,
  RuntimeHostCapabilityFuncModule,
  RuntimeHostCapabilityGlobalModule,
  RuntimeHostCapabilityKind,
  RuntimeHostCapabilityFieldScheme,
  RuntimeHostCapabilityGlobalField,
  RuntimeHostCapabilityFuncFamilyFieldScheme,
  RuntimeHostCapabilityExportPublication,
  RuntimeHostCapabilityHostSelectionEnvVar,
  RuntimeHostCapabilityHostSelectionCondition,
  RuntimeHostCapabilityHostSelection,
  RuntimeHostCapabilityFuncFamilyField,
  RuntimeHostCapabilityFuncFamilyParams,
  RuntimeHostCapabilityFuncRecord,
  RuntimeHostCapabilityGlobalRecord,
  RuntimeHostCapabilityFuncFamilyRecord,
  RuntimeHostCapabilityExportRecord,
  RuntimeHostCapabilityRecord,
  HostCallbackExceptionPolicy,
  ResolvedRuntimeHostCapabilityFuncFamilyRow,
} from "./runtime/host-capabilities.js";
