// Copyright (c) 2026 Loopdive GmbH. Licensed under Apache-2.0 WITH LLVM-exception.

export {
  STANDALONE_TIMER_CALLBACK_DISPATCH_EXPORT,
  STANDALONE_TIMER_CALLBACK_DISPATCH_PHYSICAL_BASE,
  STANDALONE_TIMER_CALLBACK_MANIFEST_EXPORT,
  STANDALONE_TIMER_CALLBACK_MANIFEST_PHYSICAL_BASE,
  STANDALONE_TIMER_CALLBACK_MARKER_EXPORT,
  STANDALONE_TIMER_CALLBACK_MARKER_PHYSICAL_BASE,
  STANDALONE_TIMER_CALLBACK_BINDINGS_EXPORT,
  STANDALONE_TIMER_CALLBACK_BINDINGS_PHYSICAL_BASE,
  STANDALONE_TIMER_CALLBACK_MANIFEST_MAGIC,
} from "./runtime/contracts/timer-capability.js";
