// Copyright (c) 2026 Loopdive GmbH. Licensed under Apache-2.0 WITH LLVM-exception.
/**
 * C header file (.h) generator for C ABI wasm exports.
 *
 * Generates a C header with function declarations matching the
 * C ABI wasm exports, suitable for use from C/C++ code that
 * links against the generated wasm module.
 */

import type { ValType, WasmModule } from "../ir/types.js";
import { absoluteFuncIndexCached } from "./resolve-layout.js"; // (#1916 S3)

/** Information about a single exported function for C header generation */
export interface CHeaderExport {
  /** C function name */
  name: string;
  /** Wasm parameter types */
  params: ValType[];
  /** Wasm result types */
  results: ValType[];
}

/**
 * Map a wasm ValType to a C type string.
 */
function wasmTypeToCType(type: ValType): string {
  switch (type.kind) {
    case "i32":
      return "int32_t";
    case "i64":
      return "int64_t";
    case "f32":
      return "float";
    case "f64":
      return "double";
    default:
      return "int32_t"; // pointers, refs → i32 in linear memory
  }
}

/**
 * Generate a C header file for the exported functions.
 *
 * @param moduleName - Used for the include guard (e.g. "my_module" → MY_MODULE_H)
 * @param exports - List of exported functions with their signatures
 * @returns The C header file content as a string
 */
export function generateCHeader(moduleName: string, exports: CHeaderExport[]): string {
  const guard = moduleName.toUpperCase().replace(/[^A-Z0-9]/g, "_") + "_H";

  const lines: string[] = [];
  lines.push("// Generated by js2wasm");
  lines.push(`#ifndef ${guard}`);
  lines.push(`#define ${guard}`);
  lines.push("");
  lines.push("#include <stdint.h>");
  lines.push("");

  for (const exp of exports) {
    // Skip memory and non-function exports
    if (exp.name === "memory") continue;

    const returnType = exp.results.length === 0 ? "void" : wasmTypeToCType(exp.results[0]!);

    const paramList =
      exp.params.length === 0 ? "void" : exp.params.map((p, i) => `${wasmTypeToCType(p)} p${i}`).join(", ");

    // If there are multiple return values (e.g. string returning ptr+len),
    // we model this as a struct return in the header comment but use the
    // first return value as the actual C return type, with out-params for
    // additional returns.
    if (exp.results.length > 1) {
      // Multiple returns: first is the return value, rest become out-params
      const outParams = exp.results
        .slice(1)
        .map((r, i) => `${wasmTypeToCType(r)}* out_${i}`)
        .join(", ");
      const allParams = exp.params.length === 0 ? outParams : `${paramList}, ${outParams}`;
      lines.push(`${returnType} ${exp.name}(${allParams});`);
    } else {
      lines.push(`${returnType} ${exp.name}(${paramList});`);
    }
  }

  lines.push("");
  lines.push(`#endif /* ${guard} */`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Extract C header export info from a WasmModule.
 * Only includes function exports (not memory, tables, etc.)
 */
export function extractCHeaderExports(mod: WasmModule): CHeaderExport[] {
  const numImportFuncs = mod.imports.filter((i) => i.desc.kind === "func").length;
  const result: CHeaderExport[] = [];

  for (const exp of mod.exports) {
    if (exp.desc.kind !== "func") continue;
    if (exp.name === "memory") continue;

    // (#1916 S3) normalize a possibly-stable handle to the absolute index.
    const funcIdx = absoluteFuncIndexCached(mod, numImportFuncs, exp.desc.index);
    const localIdx = funcIdx - numImportFuncs;
    if (localIdx < 0 || localIdx >= mod.functions.length) continue;

    const func = mod.functions[localIdx]!;
    const typeDef = mod.types[func.typeIdx];
    if (!typeDef || typeDef.kind !== "func") continue;

    result.push({
      name: exp.name,
      params: typeDef.params,
      results: typeDef.results,
    });
  }

  return result;
}
